import "./globals.css";
// core styles are required for all packages
import "@mantine/core/styles.css";
import { createTheme, MantineProvider } from "@mantine/core";
import { Header } from "@/components/Header/Header";
import { Metadata } from "next";
import { UserProvider } from "@/contexts/userContext";

const theme = createTheme(
  {
    /** Put your mantine theme override here */
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <MantineProvider theme={theme}>
            <Header />
            {children}
          </MantineProvider>
        </UserProvider>
      </body>
    </html>
  );
}
